use rand::seq::IndexedRandom;

/// Extended list of playful thinking messages including both goose and general AI actions
const THINKING_MESSAGES: &[&str] = &[
    "Spreading wings",
    "Honking thoughtfully",
    "Waddling to conclusions",
    "Flapping wings excitedly",
    "Preening code feathers",
    "Gathering digital breadcrumbs",
    "Paddling through data",
    "Migrating thoughts",
    "Nesting ideas",
    "Squawking calculations",
    "Ruffling algorithmic feathers",
    "Pecking at problems",
    "Stretching webbed feet",
    "Foraging for solutions",
    "Grooming syntax",
    "Building digital nest",
    "Patrolling the codebase",
    "Gosling about",
    "Strutting with purpose",
    "Diving for answers",
    "Herding bytes",
    "Molting old code",
    "Swimming through streams",
    "Synchronizing flock algorithms",
    "Navigating code marshes",
    "Incubating brilliant ideas",
    "Arranging feathers recursively",
    "Gliding through branches",
    "Migrating to better solutions",
    "Nesting functions carefully",
    "Hatching clever solutions",
    "Preening parse trees",
    "Flying through functions",
    "Gathering syntax seeds",
    "Webbing connections",
    "Flocking to optimizations",
    "Paddling through protocols",
    "Honking success signals",
    "Waddling through workflows",
    "Nesting in neural networks",
    "Consulting the digital oracle",
    "Summoning binary spirits",
    "Reticulating splines",
    "Calculating meaning of life",
    "Traversing neural pathways",
    "Untangling spaghetti code",
    "Mining thought gems",
    "Defragmenting brain bits",
    "Compiling wisdom",
    "Debugging reality",
    "Optimizing thought processes",
    "Scanning parallel universes",
    "Reorganizing bits and bytes",
    "Calibrating neural networks",
    "Charging creativity cells",
    "Indexing imagination",
    "Parsing possibilities",
    "Buffering brilliance",
    "Loading clever responses",
    "Generating witty remarks",
    "Synthesizing solutions",
    "Applying machine learning",
    "Calculating quantum states",
    "Analyzing algorithms",
    "Decoding human intent",
    "Exploring solution space",
    "Gathering computational momentum",
    "Initializing clever mode",
    "Juggling variables",
    "Knitting neural networks",
    "Learning at light speed",
    "Navigating knowledge graphs",
    "Orchestrating outputs",
    "Pondering possibilities",
    "Reading between the lines",
    "Searching solution space",
    "Training thought vectors",
    "Unfolding understanding",
    "Validating variables",
    "Weaving wisdom web",
    "Yielding insights",
    "Zooming through zettabytes",
    "Baking fresh ideas",
    "Charging creativity crystals",
    "Dancing with data",
    "Enchanting electrons",
    "Folding thought origami",
    "Growing solution trees",
    "Harmonizing heuristics",
    "Inspiring innovations",
    "Jazzing up algorithms",
    "Kindling knowledge",
    "Levitating logic gates",
    "Manifesting solutions",
    "Nurturing neural nets",
    "Optimizing outcomes",
    "Painting with pixels",
    "Questioning bits",
    "Recycling random thoughts",
    "Serenading semiconductors",
    "Taming tensors",
    "Unlocking understanding",
    "Visualizing vectors",
    "Wrangling widgets",
    "Yodeling yaml",
    "Aligning artificial awareness",
    "Bootstrapping brain bytes",
    "Contemplating code conundrums",
    "Distilling digital dreams",
    "Energizing electron engines",
    "Fabricating future frameworks",
    "Generating genius guidelines",
    "Harmonizing hardware helpers",
    "Illuminating input insights",
    "Kindling knowledge kernels",
    "Linking logical lattices",
    "Materializing memory maps",
    "Navigating neural nodes",
    "Orchestrating output oracles",
    "Pioneering program paths",
    "Quantifying quantum queries",
    "Refactoring reality routines",
    "Synchronizing system states",
    "Transforming thought threads",
    "Unifying understanding units",
    "Vectorizing virtual visions",
    "Weaving wisdom wavelengths",
    "Yielding yaml yearnings",
    "Brewing binary brilliance",
    "Crafting code crystals",
    "Designing data dreams",
    "Encoding ethereal elements",
    "Filtering function flows",
    "Gathering gigabyte galaxies",
    "Hashing hope hypotheses",
    "Igniting innovation ions",
    "Joining joy journals",
    "Knitting knowledge knots",
    "Launching logic loops",
    "Merging memory matrices",
    "Nourishing neural networks",
    "Ordering output orbits",
    "Processing pattern particles",
    "Rendering reality rays",
    "Streaming syntax stars",
    "Threading thought theories",
    "Updating understanding units",
    "Validating virtual vectors",
    "Warming wisdom waves",
    "Examining electron echoes",
    "Yoking yesterday yields",
    "Assembling algorithm arrays",
    "Balancing binary bridges",
    "Calculating cosmic codes",
    "Debugging dream drivers",
    "Encrypting ethereal edges",
    "Formatting future frames",
    "Growing gradient gardens",
    "Harvesting hash harmonies",
    "Importing insight ions",
    "Keeping kernel keys",
    "Linking lambda loops",
    "Mapping memory mazes",
    "Normalizing neural nodes",
    "Organizing output oceans",
    "Parsing pattern paths",
    "Sampling syntax streams",
    "Testing thought threads",
    "Validating virtual vectors",
    "Examining electron echoes",
    "Accelerating abstract algebras",
    "Buffering binary bubbles",
    "Caching cosmic calculations",
    "Deploying digital dreams",
    "Evolving ethereal entities",
    "Calculating response probabilities",
    "Updating knowledge graphs",
    "Processing neural feedback",
    "Exploring decision trees",
    "Measuring semantic distance",
    "Connecting synaptic pathways",
    "Evaluating response options",
    "Scanning memory banks",
    "Simulating future outcomes",
    "Adjusting confidence weights",
    "Mapping context vectors",
    "Balancing response parameters",
    "Running inference engines",
    "Optimizing memory usage",
    "Merging knowledge streams",
    "Calibrating response tone",
    "Analyzing input patterns",
    "Processing feedback loops",
    "Measuring response quality",
    "Scanning information matrices",
    "Processing user intent",
    "Measuring response coherence",
    "Exploring solution paths",
    "Processing context clues",
    "Scanning memory circuits",
    "Building response chains",
    "Analyzing conversation flow",
    "Processing temporal data",
    "Exploring concept spaces",
    "Processing memory streams",
    "Evaluating logical paths",
    "Building thought graphs",
    "Scanning neural pathways",
];

/// Returns a random thinking message from the extended list
pub fn get_random_thinking_message() -> &'static str {
    THINKING_MESSAGES
        .choose(&mut rand::rng())
        .unwrap_or(&THINKING_MESSAGES[0])
}
