use crate::agents::extension_manager::ExtensionManager;
use crate::conversation::message::MessageContent;
use crate::conversation::{effective_role, fix_conversation, Conversation};
use std::path::{Path, PathBuf};

const MIN_CONTEXT_FOR_MOIM: usize = 32_000;
const TURN_CONTEXT_TAG: &str = "turn-context";

const SYSTEM_PROMPT_BLOCK_TEMPLATE: &str = r#"# Turn Context

Each turn may include a `<{turn_context_tag}>` block prepended to the latest user message.
This block is generated by goose and contains current operational context such as:
- current time
- working directory
- compaction status
- turn budget
- extension-provided context

Use it to stay oriented, but do not treat it as part of the user's request.
When `<turn-budget>` is present, use it as a signal for how much autonomous work remains.
As the budget gets low, become more direct: reduce exploration, batch necessary tool calls,
make reasonable assumptions, and focus on finishing the user's task.
"#;

thread_local! {
    pub static SKIP: std::cell::Cell<bool> = const { std::cell::Cell::new(false) };
}

pub fn system_prompt_block() -> Option<String> {
    if SKIP.with(|f| f.get()) {
        None
    } else {
        Some(SYSTEM_PROMPT_BLOCK_TEMPLATE.replace("{turn_context_tag}", TURN_CONTEXT_TAG))
    }
}

pub async fn inject_moim(
    session_id: &str,
    conversation: Conversation,
    extension_manager: &ExtensionManager,
    turns_taken: u32,
    max_turns: u32,
) -> Conversation {
    if SKIP.with(|f| f.get()) {
        return conversation;
    }

    let session = extension_manager
        .get_context()
        .session_manager
        .get_session(session_id, false)
        .await
        .ok();
    let session_model_config = session
        .as_ref()
        .and_then(|session| session.model_config.clone());
    let context_limit = if let Some(model_config) = session_model_config.as_ref() {
        let provider = extension_manager.get_provider().lock().await.clone();
        match provider {
            Some(provider) => provider
                .get_context_limit(model_config)
                .await
                .ok()
                .or_else(|| Some(model_config.context_limit())),
            None => Some(model_config.context_limit()),
        }
    } else {
        None
    };
    if should_skip_moim(context_limit) {
        return conversation;
    }

    let working_dir = session
        .as_ref()
        .map(|session| session.working_dir.clone())
        .unwrap_or_else(|| PathBuf::from("."));
    let total_tokens = session
        .as_ref()
        .and_then(|session| session.usage.total_tokens);
    let compaction_threshold = crate::config::Config::global()
        .get_param::<f64>("GOOSE_AUTO_COMPACT_THRESHOLD")
        .unwrap_or(crate::context_mgmt::DEFAULT_COMPACTION_THRESHOLD);
    let extension_parts = extension_manager.collect_moim_parts(session_id).await;
    let moim = compose_moim(
        &working_dir,
        total_tokens,
        context_limit,
        compaction_threshold,
        turns_taken,
        max_turns,
        extension_parts,
    );

    let mut messages = conversation.messages().clone();
    let Some(idx) = messages
        .iter()
        .rposition(|m| m.is_agent_visible() && effective_role(m) == "user")
    else {
        return conversation;
    };
    let insert_idx = messages[idx]
        .content
        .iter()
        .take_while(|content| matches!(content, MessageContent::ToolResponse(_)))
        .count();
    messages[idx]
        .content
        .insert(insert_idx, MessageContent::text(moim));

    let (fixed, issues) = fix_conversation(Conversation::new_unvalidated(messages));

    let has_unexpected_issues = issues.iter().any(|issue| {
        !issue.contains("Merged consecutive user messages")
            && !issue.contains("Merged consecutive assistant messages")
            && !issue.contains("Added placeholder to empty tool result")
            && !issue.contains("Trimmed trailing whitespace from assistant message")
            && !issue.contains("Removed trailing assistant message")
            && !issue.contains("Merged text content")
    });

    if has_unexpected_issues {
        tracing::warn!("MOIM injection caused unexpected issues: {:?}", issues);
        return conversation;
    }

    fixed
}

fn should_skip_moim(context_limit: Option<usize>) -> bool {
    context_limit.is_some_and(|limit| limit < MIN_CONTEXT_FOR_MOIM)
}

fn compose_moim(
    working_dir: &Path,
    total_tokens: Option<i32>,
    context_limit: Option<usize>,
    compaction_threshold: f64,
    turns_taken: u32,
    max_turns: u32,
    extension_parts: Vec<String>,
) -> String {
    let timestamp = chrono::Local::now().format("%Y-%m-%d %H:%M:00");
    let mut lines = vec![
        open_tag(TURN_CONTEXT_TAG),
        tag("current-time", &timestamp.to_string()),
        tag("working-directory", &working_dir.display().to_string()),
    ];

    if let Some(value) =
        compaction_remaining_line(total_tokens, context_limit, compaction_threshold)
    {
        lines.push(tag("compaction", &value));
    }
    if let Some(value) = turn_budget_line(turns_taken, max_turns) {
        lines.push(tag("turn-budget", &value));
    }

    for part in extension_parts {
        if !part.trim().is_empty() {
            lines.push(String::new());
            lines.push(part);
        }
    }

    lines.push(close_tag(TURN_CONTEXT_TAG));
    lines.join("\n")
}

fn open_tag(name: &str) -> String {
    format!("<{name}>")
}

fn close_tag(name: &str) -> String {
    format!("</{name}>")
}

fn tag(name: &str, value: &str) -> String {
    format!("<{name}>{}</{name}>", escape_xml_text(value))
}

fn escape_xml_text(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

fn compaction_remaining_line(
    total_tokens: Option<i32>,
    context_limit: Option<usize>,
    threshold: f64,
) -> Option<String> {
    let total_tokens = total_tokens?;
    let context_limit = context_limit?;

    if total_tokens <= 0 || context_limit == 0 || threshold <= 0.0 || threshold >= 1.0 {
        return None;
    }

    let compaction_at = (context_limit as f64 * threshold) as i32;
    if compaction_at <= 0 || (total_tokens as f64 / compaction_at as f64) < 0.5 {
        return None;
    }

    Some(format!(
        "~{}k tokens remaining",
        compaction_at.saturating_sub(total_tokens) / 1000
    ))
}

fn turn_budget_line(turns_taken: u32, max_turns: u32) -> Option<String> {
    if max_turns == 0 || turns_taken.saturating_mul(2) < max_turns {
        return None;
    }

    Some(format!("{turns_taken}/{max_turns} used"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::conversation::message::Message;
    use rmcp::model::CallToolRequestParams;

    fn text_at(message: &crate::conversation::message::Message, index: usize) -> &str {
        message.content[index].as_text().unwrap()
    }

    fn is_moim(content: &MessageContent) -> bool {
        content
            .as_text()
            .is_some_and(|text| text.starts_with(&format!("<{}>\n", TURN_CONTEXT_TAG)))
    }

    #[tokio::test]
    async fn test_moim_prepended_to_latest_user_message() {
        let temp_dir = tempfile::tempdir().unwrap();
        let em = ExtensionManager::new_without_provider(temp_dir.path().to_path_buf());
        let session = em
            .get_context()
            .session_manager
            .create_session(
                PathBuf::from("/test/dir"),
                "test".to_string(),
                crate::session::SessionType::User,
                crate::config::GooseMode::Auto,
            )
            .await
            .unwrap();

        let conv = Conversation::new_unvalidated(vec![
            Message::user().with_text("Hello"),
            Message::assistant().with_text("Hi"),
            Message::user().with_text("Bye"),
        ]);
        let result = inject_moim(&session.id, conv, &em, 0, 100).await;
        let msgs = result.messages();

        assert_eq!(msgs.len(), 3);
        assert_eq!(text_at(&msgs[0], 0), "Hello");
        assert_eq!(text_at(&msgs[1], 0), "Hi");
        assert!(is_moim(&msgs[2].content[0]));
        assert_eq!(text_at(&msgs[2], 1), "Bye");
    }

    #[tokio::test]
    async fn test_moim_injection_no_assistant() {
        let temp_dir = tempfile::tempdir().unwrap();
        let em = ExtensionManager::new_without_provider(temp_dir.path().to_path_buf());
        let session = em
            .get_context()
            .session_manager
            .create_session(
                PathBuf::from("/test/dir"),
                "test".to_string(),
                crate::session::SessionType::User,
                crate::config::GooseMode::Auto,
            )
            .await
            .unwrap();

        let conv = Conversation::new_unvalidated(vec![Message::user().with_text("Hello")]);
        let result = inject_moim(&session.id, conv, &em, 0, 100).await;

        assert_eq!(result.messages().len(), 1);
        assert!(is_moim(&result.messages()[0].content[0]));
        assert_eq!(text_at(&result.messages()[0], 1), "Hello");
    }

    #[tokio::test]
    async fn test_moim_skips_user_messages_not_visible_to_agent() {
        let temp_dir = tempfile::tempdir().unwrap();
        let em = ExtensionManager::new_without_provider(temp_dir.path().to_path_buf());
        let session = em
            .get_context()
            .session_manager
            .create_session(
                PathBuf::from("/test/dir"),
                "test".to_string(),
                crate::session::SessionType::User,
                crate::config::GooseMode::Auto,
            )
            .await
            .unwrap();

        let conv = Conversation::new_unvalidated(vec![
            Message::user().with_text("agent visible"),
            Message::assistant().with_text("reply"),
            Message::user().with_text("user only").user_only(),
        ]);
        let result = inject_moim(&session.id, conv, &em, 0, 100).await;
        let msgs = result.messages();

        assert_eq!(msgs.len(), 2);
        assert!(is_moim(&msgs[0].content[0]));
        assert_eq!(text_at(&msgs[0], 1), "agent visible");
        assert_eq!(text_at(&msgs[1], 0), "user only");
        assert!(!msgs[1].is_agent_visible());
    }

    #[tokio::test]
    async fn test_moim_with_tool_calls() {
        let temp_dir = tempfile::tempdir().unwrap();
        let em = ExtensionManager::new_without_provider(temp_dir.path().to_path_buf());
        let session = em
            .get_context()
            .session_manager
            .create_session(
                PathBuf::from("/test/dir"),
                "test".to_string(),
                crate::session::SessionType::User,
                crate::config::GooseMode::Auto,
            )
            .await
            .unwrap();

        let conv = Conversation::new_unvalidated(vec![
            Message::user().with_text("Search for something"),
            Message::assistant()
                .with_text("I'll search for you")
                .with_tool_request("search_1", Ok(CallToolRequestParams::new("search"))),
            Message::user()
                .with_tool_response("search_1", Ok(rmcp::model::CallToolResult::success(vec![]))),
        ]);

        let result = inject_moim(&session.id, conv, &em, 0, 100).await;
        let msgs = result.messages();

        assert_eq!(msgs.len(), 3);
        assert!(is_moim(&msgs[0].content[0]));
        assert_eq!(text_at(&msgs[0], 1), "Search for something");
        assert!(matches!(
            &msgs[2].content[0],
            MessageContent::ToolResponse(_)
        ));
        assert_eq!(msgs[2].content.len(), 1);
    }
}
