name: "Cargo Deny"
on:
  push:
    paths:
      # Run if workflow changes
      - '.github/workflows/cargo-deny.yml'
      # Run on changed dependencies
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      # Run if the configuration file changes
      - 'deny.toml'
  # Rerun periodically to pick up new advisories
  schedule:
    - cron: '0 0 * * *'
  # Run manually
  workflow_dispatch:

jobs:
  deny:
    runs-on: ubuntu-latest
    if: github.repository == 'aaif-goose/goose'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      # https://github.com/EmbarkStudios/cargo-deny-action v2.0.15
      - uses: EmbarkStudios/cargo-deny-action@bb137d7af7e4fb67e5f82a49c4fce4fad40782fe
        with:
          command: check advisories
